# Cloudflare Tunnel for the docker services
networks:
  cloudflared:
    external: true
  tsdproxy:
    external: true

services:
  unsloth-amd:
    networks:
      - cloudflared
      - tsdproxy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "unsloth-amd"
      # tsdproxy.autodetect: "true"
      tsdproxy.port.1: "443/https:8888/http"
      tsdproxy.port.2: "8888/http:8888/http"
      # tsdproxy.container_port: "8888"

#   unsloth-planner:
#     networks:
#       - cloudflared
#       - tsdproxy
#     labels:
#       tsdproxy.enable: "true"
#       tsdproxy.name: "unsloth-planner"
#       tsdproxy.port.1: "443/https:8888/http"
#       tsdproxy.port.2: "8888/http:8888/http"
#       # tsdproxy.autodetect: "true"
#       # tsdproxy.container_port: "8888"

  unsloth-builder:
    networks:
      - cloudflared
      - tsdproxy
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "unsloth-builder"
      tsdproxy.port.1: "443/https:8888/http"
      tsdproxy.port.2: "8888/http:8888/http"
      # tsdproxy.autodetect: "true"
      # tsdproxy.container_port: "8888"